"""Create SMSSetting for admin-controlled OTP testing flag

Generated by assistant
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("allow_plaintext_otp", models.BooleanField(default=False)),
            ],
            options={},
        ),
    ]
