# Generated by Django 6.0 on 2025-12-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_smssetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smssetting',
            options={'verbose_name': 'SMS Setting', 'verbose_name_plural': 'SMS Settings'},
        ),
    ]
