# Generated by Django 6.0 on 2026-01-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='first_order_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_order_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_orders',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
