# Generated by Django 6.0 on 2026-01-02 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_employee_role_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercode',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='smssetting',
            options={},
        ),
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 2, 8, 37, 47, 106765, tzinfo=datetime.timezone.utc), help_text='OTP expiry timestamp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional. For receipts / future communication.', max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_order_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of first successful order', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft disable customer if needed'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_order_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of most recent order', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, help_text='Optional. Asked on first successful order.', max_length=120),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(db_index=True, help_text='Primary identifier (OTP based login)', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_orders',
            field=models.PositiveIntegerField(default=0, help_text='Total completed orders'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(help_text='6-digit numeric OTP', max_length=6),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='accounts_cu_phone_106324_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_at'], name='accounts_cu_created_242e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['expires_at'], name='accounts_ot_expires_57ad4f_idx'),
        ),
        migrations.DeleteModel(
            name='UserCode',
        ),
    ]
