# Generated by Django 5.2.6 on 2026-01-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_otp_used_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='auth_provider',
            field=models.CharField(choices=[('phone', 'Phone OTP'), ('google', 'Google OAuth')], default='phone', help_text='Authentication method used', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='google_email',
            field=models.EmailField(blank=True, help_text='Email from Google OAuth', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='google_id',
            field=models.CharField(blank=True, help_text='Google user ID for OAuth login', max_length=50, null=True, unique=True),
        ),
    ]
