# Generated by Django 6.0 on 2026-01-04 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='google_email',
            field=models.EmailField(blank=True, help_text='Email returned by Google OAuth', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='google_id',
            field=models.CharField(blank=True, help_text='Google OAuth user ID', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Linked Django user for session auth', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(help_text='Numeric OTP', max_length=6),
        ),
    ]
