# Generated by Django 5.2 on 2026-01-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customer_google_email_alter_customer_google_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Customer preferences stored as JSON (e.g., dietary restrictions, favorite items)'),
        ),
    ]
