# Generated by Django 6.0 on 2026-01-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_ingredientmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=16, null=True, unique=True),
        ),
    ]
