# Generated by Django 6.0 on 2026-01-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_ingredient_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(blank=True, help_text='Optional ingredient category', max_length=64),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='expiry_days',
            field=models.PositiveIntegerField(blank=True, help_text='Shelf life in days (optional)', null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='preferred_vendor',
            field=models.CharField(blank=True, help_text='Preferred vendor name (optional)', max_length=120),
        ),
    ]
