# Generated by Django 6.0 on 2026-01-04 08:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_ingredient_category_ingredient_expiry_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='code',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Auto-generated ERP code (ING-0001)', max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='₹ per base unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='expiry_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fallback_cost_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Used ONLY when stock is zero and fallback is enabled', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='preferred_vendor',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='stock_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Stock in base unit only (kg / ltr / pcs)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
    ]
