# Generated by Django 5.2 on 2026-01-05 20:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_alter_ingredient_category_alter_ingredient_code_and_more'),
        ('menu', '0024_prepareditem_batch_output_quantity_and_more'),
        ('orders', '0014_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='stock_qty',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='_stock_qty',
            field=models.DecimalField(db_column='stock_qty', decimal_places=3, default=Decimal('0.000'), help_text='DEPRECATED: Stock calculated from ledger entries', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.CreateModel(
            name='IngredientStockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('opening', 'Opening Stock'), ('purchase', 'Purchase'), ('consumption', 'Consumption'), ('adjustment', 'Adjustment'), ('wastage', 'Wastage')], max_length=12)),
                ('quantity_change', models.DecimalField(decimal_places=3, help_text='Positive for additions, negative for reductions', max_digits=12)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('ltr', 'Litre'), ('pcs', 'Pieces')], help_text="Must match ingredient's base unit", max_length=10)),
                ('note', models.TextField(blank=True, help_text='Reason for change, supplier details, etc.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger', to='ingredients.ingredient')),
                ('related_combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_consumptions', to='menu.combo')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_consumptions', to='orders.order')),
                ('related_prepared_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_consumptions', to='menu.prepareditem')),
            ],
            options={
                'verbose_name': 'Stock Ledger Entry',
                'verbose_name_plural': 'Stock Ledger Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
