# Generated by Django 5.2 on 2026-01-06 09:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_remove_ingredient_stock_qty_ingredient__stock_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='_stock_qty',
            field=models.DecimalField(db_column='stock_qty', decimal_places=3, default=Decimal('0.000'), editable=False, help_text='⚠️  DEPRECATED: Kept for migration safety only. Use stock_qty property instead.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
    ]
