# Generated by Django 6.0 on 2025-12-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_snack'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ordersnack',
            new_name='orders_orde_order_i_f3c5a6_idx',
            old_name='orders_orde_order_sn_8d3f6b_idx',
        ),
    ]
