# Generated by Django 6.0 on 2025-12-31 11:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_prepareditem_sell_only_in_combo_and_more'),
        ('orders', '0003_rename_orders_orde_order_sn_8d3f6b_idx_orders_orde_order_i_f3c5a6_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersnack',
            name='price',
        ),
        migrations.AddField(
            model_name='ordersnack',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordercombo',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_combos', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='ordersnack',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_snacks', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='ordersnack',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='ordercombo',
            index=models.Index(fields=['order'], name='orders_orde_order_i_318224_idx'),
        ),
    ]
