# Generated by Django 6.0 on 2026-01-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_address_cart_cartline'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online'), ('cod', 'Cash on Delivery')], db_index=True, default='online', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
