# Generated by Django 5.2.6 on 2026-01-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_metadata_orderevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='eta_minutes',
            field=models.PositiveIntegerField(default=37, help_text='Estimated time to delivery in minutes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
