# Generated by Django 5.2 on 2026-01-06 12:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_scheduled',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this order is scheduled for later preparation'),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='When the order should be prepared/delivered', null=True),
        ),
        migrations.CreateModel(
            name='OrderAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_type', models.CharField(choices=[('global', 'Global Order Addon'), ('combo', 'Combo'), ('item', 'Prepared Item'), ('snack', 'Snack')], max_length=16)),
                ('combo_id', models.UUIDField(blank=True, null=True)),
                ('prepared_item_id', models.UUIDField(blank=True, null=True)),
                ('snack_id', models.BigIntegerField(blank=True, null=True)),
                ('addon_name', models.CharField(max_length=120)),
                ('addon_category', models.CharField(blank=True, max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_addons', to='orders.order')),
            ],
            options={
                'indexes': [models.Index(fields=['order'], name='orders_orde_order_i_210de9_idx')],
            },
        ),
    ]
