# Generated by Django 6.0 on 2025-12-27 18:43

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('mixture', 'Mixture'), ('chips', 'Chips'), ('sweet', 'Sweet'), ('savory', 'Savory')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='snacks/')),
                ('weight_label', models.CharField(blank=True, help_text='e.g. 200g, 500g, 1kg', max_length=50)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock_qty', models.PositiveIntegerField(default=0, help_text='Number of packets available')),
                ('is_veg', models.BooleanField(default=True)),
                ('is_spicy', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('source_name', models.CharField(blank=True, help_text='Wholesaler / Partner name (internal use)', max_length=120)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'weight_label')},
            },
        ),
    ]
