# Generated by Django 5.2.6 on 2025-12-28 10:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Wholesale / buying price (internal)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='snack',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum Retail Price shown to customers', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
