# Generated by Django 6.0 on 2025-12-29 07:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_snack_buying_price_snack_mrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='locked_cost_per_pack',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional: locked cost per pack when not using batch-cost model.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='snack',
            name='pack_size',
            field=models.CharField(blank=True, help_text='Fixed pack size (e.g. 50g, 100g). Must be set for all snacks.', max_length=32),
        ),
        migrations.CreateModel(
            name='SnackBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_code', models.CharField(blank=True, help_text='Optional batch code (e.g. BATCH-20251229)', max_length=32)),
                ('batch_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('packs_produced', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cost_per_pack', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('units_remaining', models.PositiveIntegerField()),
                ('supplier_name', models.CharField(blank=True, help_text='Trader / supplier name (optional)', max_length=120)),
                ('received', models.BooleanField(default=False, help_text='Mark true when batch is received into stock')),
                ('received_date', models.DateField(blank=True, null=True)),
                ('produced_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='snacks.snack')),
            ],
            options={
                'ordering': ['-produced_at'],
            },
        ),
    ]
