# Generated by Django 6.0 on 2025-12-31 11:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0003_snack_locked_cost_per_pack_snack_pack_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fallback cost if no batch exists', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='snack',
            name='locked_cost_per_pack',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional locked cost per pack.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='snack',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='snack',
            name='pack_size',
            field=models.CharField(help_text='Fixed pack size (e.g. 50g, 100g). Required.', max_length=32),
        ),
        migrations.AlterField(
            model_name='snack',
            name='source_name',
            field=models.CharField(blank=True, help_text='Wholesaler / Partner (internal)', max_length=120),
        ),
        migrations.AlterField(
            model_name='snack',
            name='stock_qty',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Derived from received SnackBatches'),
        ),
        migrations.AlterField(
            model_name='snackbatch',
            name='batch_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='snackbatch',
            name='received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='snackbatch',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
