# Generated by Django 6.0 on 2026-01-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0005_snack_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='animated_image',
            field=models.ImageField(blank=True, help_text='Optional animated preview (gif/webp) used on product cards', null=True, upload_to='snacks/animated/'),
        ),
        migrations.AddField(
            model_name='snack',
            name='badge_text',
            field=models.CharField(blank=True, help_text='Optional custom badge text (e.g. Best Buy)', max_length=32),
        ),
        migrations.AddField(
            model_name='snack',
            name='is_best_buy',
            field=models.BooleanField(default=False, help_text='Flag to show a prominent badge on frontend'),
        ),
        migrations.AddField(
            model_name='snack',
            name='offers',
            field=models.TextField(blank=True, default='', help_text='Promotional offer text shown on product card'),
        ),
    ]
