# Generated by Django 5.2 on 2026-01-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0006_snack_animated_image_snack_badge_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='region',
            field=models.CharField(choices=[('chettinad', 'Chettinad'), ('andhra', 'Andhra'), ('kerala', 'Kerala'), ('karnataka', 'Karnataka'), ('tamil_nadu', 'Tamil Nadu'), ('other', 'Other')], default='other', help_text='Regional origin for branding and curation', max_length=20),
        ),
    ]
