# Generated by Django 5.2 on 2026-01-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0007_snack_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='min_order_qty',
            field=models.PositiveIntegerField(default=1, help_text='Minimum quantity required for delivery (trust & UX)'),
        ),
    ]
