# Generated by Django 5.2 on 2026-01-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0008_snack_min_order_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='pairs_with',
            field=models.JSONField(default=list, help_text="e.g. ['Idli', 'Sambar'] - items this snack pairs well with"),
        ),
    ]
