# Generated by Django 5.2 on 2026-01-06 14:42

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0009_snack_pairs_with'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnackCombo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(blank=True, db_index=True, editable=False, max_length=16, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='combos/')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SnackComboItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of packs of this snack in the combo', validators=[django.core.validators.MinValueValidator(1)])),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='snacks.snackcombo')),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='snacks.snack')),
            ],
            options={
                'ordering': ['combo', 'snack__name'],
                'unique_together': {('combo', 'snack')},
            },
        ),
    ]
