# Generated by Django 6.0 on 2025-12-27 18:40

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('short_description', models.TextField(blank=True, help_text='Shown on app popup')),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('4.5'), max_digits=2)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PreparedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, help_text='Customer-facing description')),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('ml', 'Millilitre'), ('gm', 'Gram')], max_length=10)),
                ('serving_size', models.DecimalField(blank=True, decimal_places=2, help_text='Eg: 60 (gm/ml) per serving', max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cost_price_cached', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComboImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='combos/')),
                ('is_primary', models.BooleanField(default=False)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menu.combo')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PreparedItemImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='prepared_items/')),
                ('is_primary', models.BooleanField(default=False)),
                ('prepared_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menu.prepareditem')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ComboItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Number of servings / pieces', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_cached', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.combo')),
                ('prepared_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.prepareditem')),
            ],
            options={
                'unique_together': {('combo', 'prepared_item')},
            },
        ),
        migrations.CreateModel(
            name='PreparedItemRecipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_unit', models.CharField(choices=[('gm', 'Gram'), ('kg', 'Kilogram'), ('ml', 'Millilitre'), ('ltr', 'Litre'), ('pcs', 'Pieces')], default='gm', max_length=8)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingredients.ingredient')),
                ('prepared_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='menu.prepareditem')),
            ],
            options={
                'unique_together': {('prepared_item', 'ingredient')},
            },
        ),
    ]
