# Generated by Django 6.0 on 2025-12-29 06:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='code',
            field=models.CharField(blank=True, null=True, help_text='Unique code like SOT-01', max_length=16),
        ),
        migrations.AddField(
            model_name='combo',
            name='serve_person',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of persons served', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='combo',
            name='total_protein',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total protein (g) for the whole combo', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
