# Generated by Django 6.0 on 2025-12-29 06:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_populate_combo_code_and_add_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepareditem',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Protein (g) per serving/piece', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
