# Generated by Django 6.0 on 2025-12-29 06:44

import menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_add_prepareditem_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='combos/', validators=[menu.models.validate_combo_main_image]),
        ),
        migrations.AlterField(
            model_name='comboimage',
            name='image',
            field=models.ImageField(upload_to='combos/', validators=[menu.models.validate_combo_image]),
        ),
        migrations.AlterField(
            model_name='comboitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='combo_item_images/', validators=[menu.models.validate_comboitem_image]),
        ),
        migrations.AlterField(
            model_name='prepareditem',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='prepared_items/', validators=[menu.models.validate_prepared_item_image]),
        ),
        migrations.AlterField(
            model_name='prepareditemimage',
            name='image',
            field=models.ImageField(upload_to='prepared_items/', validators=[menu.models.validate_prepared_item_image]),
        ),
    ]
