# Generated by Django 6.0 on 2025-12-29 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_combo_main_image_alter_comboimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboitem',
            name='display_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final quantity shown to customer (e.g. 100 ml, 4 pcs)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='comboitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Recipe quantity (internal) — used for costing and recipes', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
