# Generated by Django 6.0 on 2025-12-29 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_comboitem_display_quantity_alter_comboitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comboitem',
            options={'ordering': ['display_order', 'id']},
        ),
        migrations.AddField(
            model_name='comboitem',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comboitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Number of prepared items (internal) — used for costing and recipes', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='prepareditem',
            name='serving_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Serving portion (e.g. 100 ml, 50 ml, 1 pcs)', max_digits=6, null=True),
        ),
    ]
