# Generated by Django 6.0 on 2025-12-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_comboitem_options_comboitem_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='hero_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='combo',
            name='is_hero',
            field=models.BooleanField(default=False, help_text='Designate this combo as the frontpage hero'),
        ),
    ]
