# Generated by Django 6.0 on 2025-12-30 15:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_combo_hero_order_combo_is_hero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combo',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='comboimage',
            options={'ordering': ('-is_primary', 'id')},
        ),
        migrations.AlterModelOptions(
            name='comboitem',
            options={'ordering': ('display_order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='prepareditem',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='prepareditemimage',
            options={'ordering': ('-is_primary', 'id')},
        ),
        migrations.AlterField(
            model_name='combo',
            name='code',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='combo',
            name='is_hero',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='combo',
            name='serve_person',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='combo',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='combo',
            name='total_protein',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=6),
        ),
        migrations.AlterField(
            model_name='comboitem',
            name='display_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='comboitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='prepareditem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prepareditem',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='prepareditem',
            name='serving_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Customer-facing serving size (e.g. 100 ml, 2 pcs)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='prepareditem',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('gm', 'Gram'), ('ml', 'Millilitre')], max_length=8),
        ),
    ]
