# Generated by Django 6.0 on 2025-12-31 07:06

import django.core.validators
import django.db.models.deletion
import menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_rename_prepareditem_protein'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepareditemimage',
            name='prepared_item',
        ),
        migrations.RenameField(
            model_name='combo',
            old_name='short_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='combo',
            old_name='serve_person',
            new_name='serve_persons',
        ),
        migrations.RemoveField(
            model_name='combo',
            name='hero_order',
        ),
        migrations.RemoveField(
            model_name='combo',
            name='is_hero',
        ),
        migrations.RemoveField(
            model_name='combo',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='combo',
            name='total_protein',
        ),
        migrations.RemoveField(
            model_name='comboitem',
            name='display_quantity',
        ),
        migrations.RemoveField(
            model_name='comboitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='prepareditem',
            name='selling_price',
        ),
        migrations.AlterField(
            model_name='combo',
            name='code',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='combo',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='combos/', validators=[menu.models.validate_image_min_600]),
        ),
        migrations.AlterField(
            model_name='combo',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='comboitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Multiplier of prepared item serving', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='prepareditem',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='prepared_items/', validators=[menu.models.validate_image_min_600]),
        ),
        migrations.AlterField(
            model_name='prepareditem',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='prepareditem',
            name='serving_size',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Customer-facing serving (e.g. 2 pcs, 100 ml)', max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prepareditemrecipe',
            name='prepared_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='menu.prepareditem'),
        ),
        migrations.DeleteModel(
            name='ComboImage',
        ),
        migrations.DeleteModel(
            name='PreparedItemImage',
        ),
    ]
