# Generated by Django 6.0 on 2025-12-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_remove_prepareditemimage_prepared_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepareditem',
            name='serving_size',
            field=models.DecimalField(decimal_places=2, help_text='Customer-facing serving (e.g. 1 pc, 50 ml)', max_digits=6),
        ),
    ]
