# Generated by Django 6.0 on 2025-12-31 07:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_alter_prepareditem_serving_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='comboitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prepareditem',
            options={},
        ),
        migrations.AlterField(
            model_name='combo',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='combo',
            name='serve_persons',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='comboitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='prepareditem',
            name='protein_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='prepareditem',
            name='serving_size',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='prepareditemrecipe',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prepareditemrecipe',
            name='quantity_unit',
            field=models.CharField(choices=[('gm', 'Gram'), ('kg', 'Kilogram'), ('ml', 'Millilitre'), ('ltr', 'Litre')], default='gm', max_length=8),
        ),
    ]
