# Generated by Django 6.0 on 2025-12-31 07:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_alter_combo_options_alter_comboitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combo',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='comboitem',
            options={'ordering': ('display_order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='prepareditem',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='combo',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='combo',
            name='serve_persons',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='comboitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='prepareditem',
            name='protein_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='prepareditem',
            name='serving_size',
            field=models.DecimalField(decimal_places=2, help_text='Customer-facing serving (e.g. 1 pc, 50 ml)', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='prepareditemrecipe',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='prepareditemrecipe',
            name='quantity_unit',
            field=models.CharField(choices=[('gm', 'Gram'), ('kg', 'Kilogram'), ('ml', 'Millilitre'), ('ltr', 'Litre'), ('pcs', 'Pieces')], default='gm', max_length=8),
        ),
    ]
