# Generated by Django 6.0 on 2025-12-31 10:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_alter_combo_options_alter_comboitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepareditem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Customer-facing price for ONE serving unit', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
            preserve_default=False,
        ),
    ]
