# Generated by Django 6.0 on 2025-12-31 10:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_prepareditem_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepareditem',
            name='sell_only_in_combo',
            field=models.BooleanField(default=True, editable=False, help_text='Prepared items cannot be ordered standalone'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='serve_persons',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='prepareditem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, help_text='Unit value used ONLY inside a Combo (not sold standalone)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
