# Generated by Django 6.0 on 2026-01-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_prepareditem_sell_only_in_combo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepareditem',
            name='code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='combo',
            name='code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=16, null=True, unique=True),
        ),
    ]
