# Generated by Django 6.0 on 2026-01-01 09:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_prepareditem_code_alter_combo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='combo_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='combo',
            name='serving_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Customer-facing serving size for the combo (optional)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='combo',
            name='serving_unit',
            field=models.CharField(blank=True, choices=[('pcs', 'Pieces'), ('gm', 'Gram'), ('ml', 'Millilitre')], max_length=8),
        ),
        migrations.AddField(
            model_name='prepareditem',
            name='recipe_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
