# Generated by Django 6.0 on 2026-01-04 08:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_combo_combo_version_combo_serving_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='serving_size',
        ),
        migrations.RemoveField(
            model_name='combo',
            name='serving_unit',
        ),
        migrations.RemoveField(
            model_name='prepareditem',
            name='protein_per_unit',
        ),
        migrations.AlterField(
            model_name='comboitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='prepareditem',
            name='sell_only_in_combo',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='prepareditem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, help_text='Internal combo unit value', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='prepareditem',
            name='serving_size',
            field=models.DecimalField(decimal_places=2, help_text='1 pc, 100 ml etc', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='prepareditem',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('ml', 'Millilitre')], max_length=8),
        ),
        migrations.AlterField(
            model_name='prepareditemrecipe',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='prepareditemrecipe',
            name='quantity_unit',
            field=models.CharField(choices=[('gm', 'Gram'), ('kg', 'Kilogram'), ('ml', 'Millilitre'), ('ltr', 'Litre'), ('pcs', 'Pieces')], max_length=8),
        ),
    ]
