# Generated by Django 5.2.6 on 2026-01-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_remove_combo_serving_size_remove_combo_serving_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Offer title/heading', max_length=200)),
                ('description', models.TextField(help_text='Detailed offer description')),
                ('short_text', models.CharField(help_text='Short text for banner display (with emojis)', max_length=100)),
                ('discount_percentage', models.PositiveIntegerField(blank=True, help_text='Discount percentage (optional)', null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed discount amount (optional)', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this offer currently active?')),
                ('start_date', models.DateTimeField(blank=True, help_text='When the offer starts', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When the offer ends', null=True)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Higher priority offers show first (1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marketing Offer',
                'verbose_name_plural': 'Marketing Offers',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
