# Generated by Django 5.2.6 on 2026-01-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_marketingoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingoffer',
            name='banner_type',
            field=models.CharField(choices=[('limited_time', 'Limited Time Offer'), ('chefs_special', "Chef's Special"), ('promotion', 'General Promotion'), ('announcement', 'Announcement')], default='promotion', help_text='Type of banner for styling and behavior', max_length=20),
        ),
    ]
