# Generated by Django 5.2 on 2026-01-05 19:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_marketingoffer_banner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepareditem',
            name='batch_output_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total output quantity for one batch (required for BATCH mode)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='prepareditem',
            name='production_mode',
            field=models.CharField(choices=[('per_serving', 'Per Serving'), ('batch', 'Batch Production')], default='per_serving', help_text='How this item is produced: per serving or in batches', max_length=12),
        ),
    ]
