# Generated by Django 5.2 on 2026-01-06 09:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_prepareditem_batch_output_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_size', models.DecimalField(decimal_places=2, help_text='Quantity prepared (in PreparedItem serving units)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When batch was prepared')),
                ('notes', models.TextField(blank=True, help_text="Kitchen notes (e.g., 'Extra spicy batch', 'Trial run')")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prepared_item', models.ForeignKey(help_text='Item being batch prepared', on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_batches', to='menu.prepareditem')),
            ],
            options={
                'verbose_name': 'Kitchen Batch',
                'verbose_name_plural': 'Kitchen Batches',
                'ordering': ['-timestamp'],
            },
        ),
    ]
