# Generated by Django 6.0 on 2026-01-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storestatus',
            options={'verbose_name': 'Store Status', 'verbose_name_plural': 'Store Status'},
        ),
        migrations.AddField(
            model_name='storestatus',
            name='close_time',
            field=models.TimeField(blank=True, help_text='Daily closing time (e.g. 11:30)', null=True),
        ),
        migrations.AddField(
            model_name='storestatus',
            name='open_time',
            field=models.TimeField(blank=True, help_text='Daily opening time (e.g. 06:00)', null=True),
        ),
        migrations.AlterField(
            model_name='storestatus',
            name='is_open',
            field=models.BooleanField(default=True, help_text='Manually force store open/closed'),
        ),
        migrations.AlterField(
            model_name='storestatus',
            name='note',
            field=models.CharField(blank=True, help_text='Optional message shown to customers', max_length=100),
        ),
    ]
