# Generated by Django 6.0 on 2026-01-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_storestatus_options_storestatus_close_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storestatus',
            name='is_open',
            field=models.BooleanField(default=True, help_text='Manual override. Turn OFF to force close store.'),
        ),
    ]
