# Generated by Django 5.2 on 2026-01-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_storestatus_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storestatus',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='storestatus',
            name='open_time',
        ),
    ]
