# Generated by Django 5.2 on 2026-01-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_storestatus_close_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Morning', 'Evening', 'Late Night'", max_length=20)),
                ('start_time', models.TimeField(help_text='Shift start time (e.g. 09:30)')),
                ('end_time', models.TimeField(help_text='Shift end time (e.g. 14:00)')),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate to close this shift')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Shift',
                'verbose_name_plural': 'Store Shifts',
                'ordering': ['start_time'],
                'unique_together': {('name',)},
            },
        ),
    ]
