# Generated by Django 5.2 on 2026-01-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_storeshift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storestatus',
            name='is_open',
        ),
        migrations.AddField(
            model_name='storestatus',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='MASTER SWITCH: Turn OFF to force close store (emergency/festival/power cut)'),
        ),
        migrations.AlterField(
            model_name='storestatus',
            name='note',
            field=models.CharField(blank=True, help_text="Optional message shown to customers (e.g., 'Closed for festival')", max_length=100),
        ),
    ]
