# Generated by Django 5.2 on 2026-01-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_is_open_to_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='storestatus',
            name='accept_orders',
            field=models.BooleanField(default=True, help_text='ACCEPT ORDERS: Turn OFF to stop accepting new orders (overload control)'),
        ),
        migrations.AddField(
            model_name='storestatus',
            name='kitchen_active',
            field=models.BooleanField(default=True, help_text='KITCHEN ACTIVE: Turn OFF to stop cooking (prep-only mode)'),
        ),
    ]
