# Generated by Django 5.2 on 2026-01-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_storestatus_accept_orders_storestatus_kitchen_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeshift',
            name='cutoff_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Minutes before end_time when orders stop being accepted (e.g. 15 = last order at 1:45 PM for 2:00 PM close)'),
        ),
    ]
