# Generated by Django 5.2 on 2026-01-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_storeshift_cutoff_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the exception', unique=True)),
                ('is_closed', models.BooleanField(default=True, help_text='True = Store closed all day, False = Store open all day')),
                ('note', models.CharField(blank=True, help_text="Reason for exception (e.g., 'Diwali Festival', 'Maintenance')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Exception',
                'verbose_name_plural': 'Store Calendar',
                'ordering': ['date'],
            },
        ),
    ]
