# Generated by Django 5.2.9 on 2026-01-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_storeexception'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakfastWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Breakfast Window', help_text="Display name (e.g., 'Breakfast Window')", max_length=50)),
                ('opens_at', models.TimeField(help_text='Breakfast window opens at (e.g., 06:00)')),
                ('closes_at', models.TimeField(help_text='Breakfast window closes at (e.g., 10:00)')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this breakfast window')),
                ('status_label', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('OPENING_SOON', 'Opening Soon')], default='CLOSED', help_text='Current status label for frontend', max_length=20)),
                ('status_message', models.CharField(blank=True, help_text="Single source of truth message (e.g., 'Opens at 9:30 AM')", max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Breakfast Window',
                'verbose_name_plural': 'Breakfast Windows',
            },
        ),
    ]
